### ISSUE TITLE
typo: 05a pytorch

### ISSUE THREAD

**Issue by raybellwaves** [MicrosoftDocs/ml-basics#10]
https://github.com/MicrosoftDocs/ml-basics/blob/master/05a%20-%20Deep%20Neural%20Networks%20(PyTorch).ipynb

# Take a look at the first 25 training features and corresponding labels

Should be

# Take a look at the first 25 training samples and corresponding labels

**Comment by GraemeMalcolm** [comment]
No. The code shows the first 25 features (x) and their corresponding labels (y)
