### ISSUE TITLE
typo: 05c pytorch

### ISSUE THREAD

**Issue by raybellwaves** [MicrosoftDocs/ml-basics#11]
https://github.com/MicrosoftDocs/ml-basics/blob/master/05c%20-%20Transfer%20Learning%20(PyTorch).ipynb

# Now print the full model, which will include the feature extraction layers of the base model and our preediction layer

to

# Now print the full model,
# which will include the feature extraction layers of the base model and our prediction layer

**Comment by GraemeMalcolm** [comment]
Thanks. Fixed
