### ISSUE TITLE
issue - 05b - Convolutional Neural Networks (Tensorflow).ipynb

### ISSUE THREAD

**Issue by zhcli** [MicrosoftDocs/ml-basics#13]
Issue at step - explore the data

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-e9600555c755> in <module>
      7 
      8 # Get the class names
----> 9 classes = os.listdir(data_folder)
     10 classes.sort()
     11 print(len(classes), 'classes:')

NameError: name 'os' is not defined

**Comment by GraemeMalcolm** [comment]
Thanks! Fixed.
