### ISSUE TITLE
Unable to run the labs

### ISSUE THREAD

**Issue by sunil-projects** [MicrosoftDocs/ml-basics#2]
Hi,

I have followed the steps as mentioned. However, when I try opening any of the ipynb files, I see a message saying reconnecting to kernel and that never happens. I am unable to continue. Could you please help? Am I missing anything?

**Comment by GraemeMalcolm** [comment]
Are you using a local installation or Codespaces?

**Comment by sunil-projects** [comment]
Hi Graeme,

I am using Codespaces

**Comment by sunil-projects** [comment]
No luck yet. Here is the screenshot of the window

![image](https://user-images.githubusercontent.com/59966199/91152296-6b8fc800-e6dc-11ea-857d-2b0d48ed715f.png)

**Comment by GraemeMalcolm** [comment]
Can you try with a different browser?
