### ISSUE TITLE
Small incorrect Penguin species name in Notebook Classification.ipynb

### ISSUE THREAD

**Issue by mfessalifi** [MicrosoftDocs/ml-basics#28]
Hi Team,
Isn't issue, but just that I love penguin and I found incorrect species name :
penguin_classes = ['Amelie', 'Gentoo', 'Chinstrap']
Is Adelie and not Amelie :)

Regards,
Faiçal

**Comment by GraemeMalcolm** [comment]
Good catch -updated.
Thanks!
