### ISSUE TITLE
Error in Data Exploration.ipynb notebook

### ISSUE THREAD

**Issue by DFMERA** [MicrosoftDocs/ml-basics#34]
When I try to run the cells 32: print(df_students.groupby(df_students.Pass).Name.count()) and cell 33: print(df_students.groupby(df_students.Pass)['StudyHours', 'Grade'].mean()) 
I get this error: ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional

I am using the Python 3.6 - AzureML Kernel.

Thank you

**Comment by GraemeMalcolm** [comment]
I can't repro this I'm afraid. I've tried with a brand new compute instance.
