### ISSUE TITLE
typo - cell 10 - 05b - Convolutional Neural Networks (Tensorflow).ipynb

### ISSUE THREAD

**Issue by CaioCavalcanti** [MicrosoftDocs/ml-basics#35]
There's a typo on cell 10 at [05b - Convolutional Neural Networks (Tensorflow).ipynb](https://github.com/MicrosoftDocs/ml-basics/blob/master/05b%20-%20Convolutional%20Neural%20Networks%20(Tensorflow).ipynb):

> **Note**: We're only using 5 epochs to **minimze** the training [...]

Should be:

> **Note**: We're only using 5 epochs to **minimize** the training  [...]

**Comment by GraemeMalcolm** [comment]
Thanks - fixed!
