### ISSUE TITLE
Feature request: html repr of pipeline

### ISSUE THREAD

**Issue by raybellwaves** [MicrosoftDocs/ml-basics#9]
Thanks for the course. You may have this later i'm only up to 02.

You may want to add the html repr functionally to visualize the scikit-learn pipeplines

https://scikit-learn.org/stable/modules/compose.html#visualizing-composite-estimators

https://scikit-learn.org/stable/auto_examples/compose/plot_column_transformer_mixed_types.html#html-representation-of-pipeline

**Comment by GraemeMalcolm** [comment]
It's a nice idea, but requires some messing around with the environment config. We want to avoid that - this is intended to be a straightforward self-paced walkthrough that "just works" in the default Azure ML compute instance environment.
